"""Report Agent — generates a structured markdown report from all analysis outputs."""
import logging
import uuid
from datetime import datetime
from pathlib import Path

from langchain_core.messages import SystemMessage, HumanMessage

from config import REPORTS_DIR

logger = logging.getLogger(__name__)

REPORT_PROMPT = """\
You are a Report Agent. Generate a professional data analysis report in Markdown.

Structure:
1. Executive Summary (2-3 sentences)
2. Question & Approach
3. Key Findings (bullet points with numbers)
4. Detailed Analysis (from the insights provided)
5. Recommendations (actionable next steps)

Rules:
- Be concise and data-driven
- Reference specific numbers
- Use proper markdown formatting
- Include chart references where applicable
- Do NOT use markdown code fences around the entire output
"""


def run_report_agent(
    llm,
    question: str,
    insights: str,
    charts: list[dict],
    processed_data: dict,
) -> dict:
    """Generate a markdown report and save it to disk."""
    logger.info("Report Agent generating report")

    chart_refs = ""
    for i, c in enumerate(charts):
        chart_refs += f"\n- Chart {i+1}: {c.get('chart_filename', 'chart.png')}"

    messages = [
        SystemMessage(content=REPORT_PROMPT),
        HumanMessage(content=f"""
Question: {question}

Insights from analysis:
{insights}

Charts generated: {chart_refs if chart_refs else 'None'}

Generate a complete professional report.
"""),
    ]

    response = llm.invoke(messages)
    report_md = response.content.strip()

    # Add metadata header
    report_id = str(uuid.uuid4())[:8]
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    full_report = f"""---
Report ID: {report_id}
Generated: {timestamp}
Question: {question}
---

{report_md}

---
*Generated by Agentic Data Analyst*
"""

    # Save report
    filename = f"report_{report_id}.md"
    filepath = REPORTS_DIR / filename
    filepath.write_text(full_report, encoding="utf-8")
    logger.info("Report saved: %s", filepath)

    return {
        "report_id": report_id,
        "report_filename": filename,
        "report_path": str(filepath),
        "report_content": full_report,
    }
